### ISSUE TITLE
Travis CI 50 minute build limit is not enough for a reliable pass

### ISSUE THREAD

**Issue by jiridanek** [skupperproject/skupper-router#1006]
https://app.travis-ci.com/github/skupperproject/skupper-router/builds/261569004

Normally, successful run on s390x takes ~48 minutes, which is very close to the 50 minute upper limit. Meaning that if some things take longer occasionally, the build times out.

**Comment by ganeshmurthy** [comment]
We are currently not using Travis CI and do not intend to. We will reopen this if we get back to Travis CI in the future.
