### ISSUE TITLE
system_tests_topology_disposition: KeyError: 'name'

### ISSUE THREAD

**Issue by jiridanek** [skupperproject/skupper-router#1041]
https://github.com/skupperproject/skupper-router/actions/runs/4585208141/jobs/8097248918#step:10:2557

```
36:             if self.state == 'topo checking' :
36:                 # In the 'topo checking' state, we send management messages to
36:                 # ask the 4 routers about their connections. Then, parsing the
36:                 # replies, we make sure that we count the expected 6 connections.
36:                 # (The 4 routers are completely connected.)
36:                 if 'OK' == event.message.properties['statusDescription']:
36:                     try:
36:                         # debug for
36:                         # https://github.com/skupperproject/skupper-router/issues/962
36: >                       connection_name = event.message.body['name']
36: E                       KeyError: 'name'
36: 
36: /home/runner/work/skupper-router/skupper-router/skupper-router/tests/system_tests_topology_disposition.py:1023: KeyError
```

This is in the new code merged by @kgiusti recently in https://github.com/skupperproject/skupper-router/pull/963

**Comment by jiridanek** [comment]
(this is a flaky fail, it passed upon rerun, https://github.com/skupperproject/skupper-router/actions/runs/4585208141/jobs/8101560431)

**Comment by kgiusti** [comment]
Perfect! That new code I added to the test dumps the message that is failing to parse. Now we have something to look at!

Looks like a test bug. The part of the code that throws the key error is expecting the response to a query for "io.skupper.router.connector" in map form. Specifically:

 {'type': 'io.skupper.router.connector', 'name': 'AB_connector',

But when the failure happens the message is not a response to a connection query. Instead it is a response to a link query.  From the test failure logs:

  body={'attributeNames': ['linkType', 'linkDir', 'linkName', 'owningAddr', 'capacity', 'undeliveredCount', 'unsettledCount', 'acceptedCount', 'rejectedCount', 'releasedCount', 'modifiedCount'],'results': [['router-control', 'out',

So there's a bug in the test state machine where it expects a different type of error.
