### ISSUE TITLE
framing-error SSL Failure: RSA_padding_check_PKCS1_type_1:block type is not 01

### ISSUE THREAD

**Issue by nicolacdnll** [skupperproject/skupper-router#1075]
Hi there,

We are deploying Skupper 1.2.3 in on-prem nodes and the controller in the cloud and when we are behind normal NATs everything works fine. However, in a setup where we are behind a firewall, Skupper fails to establish the connection with these errors:

```
# Node
SERVER (info) [C22] Connection to edge.namespace.domain.com:443 1 failed: amqp:connection:framing-error SSL Failure: error:0407006A:rsa routines:RSA_padding_check_PKCS1_type_1:block type is not 01

# Controller
(info) [C22] Accepted connection to :45671 from 172.16.87.52:38616
(info) [C22] Connection from 172.16.87.52:38616 (to :45671) failed: amqp:connection:framing-error SSL Failure: error:1409441B:SSL routines:ssl3_read_bytes:tlsv1 alert decrypt error
(info) [C23] Accepted connection to :45671 from 172.16.87.52:386890
[...]
```

The firewall, which we don't control, maps `INTERNAL-IP:INTERNAL-PORT` to our controller `edge.namespace.domain.com:443`.
And the Skupper `router` deployment has a host alias added like this:

```yaml
    hostAliases:
    - ip: "INTERNAL-IP"
    hostnames:
    - "edge.namespace.domain.com"
```

I believe that this should work, although we have some questions:
A - Are there some SSL/RSA requirements from Skupper itself? It is possible that the firewall is doing something not so transparent (e.g., changing the RSA padding) but we can't really tell.
B - Is there a way to force Skupper to skip this padding check? Disable strict SSL?
C - Does Skupper do some checksum with target `ip:port`? I wonder if this NATting with different ports and IPs is a problem.

Any help is welcome.

**Comment by ted-ross** [comment]
Hi Nicola,

When you say that the firewall maps IP:PORT to your controller, does that
mean that you registered edge.namespace.domain.com:443 with the firewall?
Did it issue a certificate for this mapping?

We've seen situations where firewalls provide the TLS endpoint and
re-encrypt, presumably so they can inspect/log the payload of the
communication.

Skupper natively wants to use end-to-end TLS between its sites.  The tokens
used to link sites together are built with this assumption.  TLS-based
ingresses are then used in "passthrough" mode to allow the end-to-end
encryption from Skupper router to Skupper router.

When this is not possible (as may be your case), the token can be modified
to contain the firewall's certificate chain and the configuration of the
token issuer (controller in your terms?) can be modified to accept the
firewall's re-encryption.  This is not yet directly supported by the
Skupper control plane, but can be made to work manually.  If this is indeed
your situation, we can provide details of what modifications are needed.

-Ted

**Comment by nicolacdnll** [comment]
Hi Ted,
Thanks for the answer.

> When you say that the firewall maps IP:PORT to your controller, does that
mean that you registered edge.namespace.domain.com:443 with the firewall?
Did it issue a certificate for this mapping?

Yes, and we don't know if the firewall issued a cert. We will ask!
And what you described does make sense to me, so let's see what the firewall owner tells us.

Thanks again.

**Comment by nicolacdnll** [comment]
Closing this as it was a human error on my side. I was using the wrong tlsKey -.-
