### ISSUE TITLE
HTTP/2 adaptor crash: Null conn pointer on DISCONNECTED event (?)

### ISSUE THREAD

**Issue by kgiusti** [skupperproject/skupper-router#1101]
Total guess as to the crash, but the panic handler is pointing towards that section of code.

*** SKUPPER-ROUTER FATAL ERROR ***
Version: f7ea108f6a2190cdd4dbfa22a585dd1289d8c9a5
Signal: 11 SIGSEGV
Process ID: 1 (skrouterd)
Thread ID: 16 (wrkr_1)

Backtrace:
[0] IP: 0x00007f91973b1df0 (/lib64/libc.so.6 + 0x0000000000054df0)
    Registers:
      RAX: 0x00000000ffffffff RDI: 0x00007f918effa970 R11: 0x00007f9174939c20
      RBX: 0x00005559241f2450 RBP: 0x00007f918effbf50 R12: 0x0000000000000000
      RCX: 0x00007f91974a22db R8:  0x0000000000000000 R13: 0x0000000000000000
      RDX: 0x0000000000000000 R9:  0x0000000000000000 R14: 0x00007f91809c7420
      RSI: 0x0000000000000002 R10: 0x00007f918effb370 R15: 0x00005559241f2450
      SP:  0x00007f918effb180

[1] IP: 0x0000555922ef87d8 (skrouterd + 0x00000000000507d8)
    Registers:
      RAX: 0x0000555922ef87d8 RDI: 0x00007f91809c7420 R11: 0x00007f9180000020
      RBX: 0x00005559241f2450 RBP: 0x00007f918effbf50 R12: 0x0000000000000000
      RCX: 0x00005559242a6c90 R8:  0x0000000000000000 R13: 0x0000000000000000
      RDX: 0x0000555922fb53d8 R9:  0x0000000000000000 R14: 0x00007f91809c7420
      RSI: 0x00005559241f2450 R10: 0x00007f91809c7690 R15: 0x00005559241f2450
      SP:  0x00007f918effbe80

[2] IP: 0x0000555922f699cc (skrouterd + 0x00000000000c19cc)
    Registers:
      RAX: 0x0000555922ef87d8 RDI: 0x00007f91809c7420 R11: 0x00007f9180000020
      RBX: 0x00005559241f2450 RBP: 0x00007f918effc120 R12: 0x00007f91809c7420
      RCX: 0x00005559242a6c90 R8:  0x0000000000000000 R13: 0x0000000000000000
      RDX: 0x0000555922fb53d8 R9:  0x0000000000000000 R14: 0x00007f91809c7420
      RSI: 0x00005559241f2450 R10: 0x00007f91809c7690 R15: 0x00005559241f2450
      SP:  0x00007f918effbf60

[3] IP: 0x0000555922f715a6 (skrouterd + 0x00000000000c95a6)
    Registers:
      RAX: 0x0000555922ef87d8 RDI: 0x00007f91809c7420 R11: 0x00007f9180000020
      RBX: 0x00007f917c303dc8 RBP: 0x00007f918effc290 R12: 0x0000000000000000
      RCX: 0x00005559242a6c90 R8:  0x0000000000000000 R13: 0x0000000000000000
      RDX: 0x0000555922fb53d8 R9:  0x0000000000000000 R14: 0x00007f91809c7420
      RSI: 0x00005559241f2450 R10: 0x00007f91809c7690 R15: 0x00005559241f2450
      SP:  0x00007f918effc130

[4] IP: 0x00007f91973fc802 (/lib64/libc.so.6 + 0x000000000009f802)
    Registers:
      RAX: 0x0000555922ef87d8 RDI: 0x00007f91809c7420 R11: 0x00007f9180000020
      RBX: 0x00007f918effd640 RBP: 0x0000000000000000 R12: 0x00007f918effd640
      RCX: 0x00005559242a6c90 R8:  0x0000000000000000 R13: 0x0000000000000002
      RDX: 0x0000555922fb53d8 R9:  0x0000000000000000 R14: 0x00007f91973fc530
      RSI: 0x00005559241f2450 R10: 0x00007f91809c7690 R15: 0x0000000000000000
      SP:  0x00007f918effc2a0

[5] IP: 0x00007f919739c314 (/lib64/libc.so.6 + 0x000000000003f314)
    Registers:
      RAX: 0x0000555922ef87d8 RDI: 0x00007f91809c7420 R11: 0x00007f9180000020
      RBX: 0x00007fff429e7920 RBP: 0x0000000000000000 R12: 0x00007f918effd640
      RCX: 0x00005559242a6c90 R8:  0x0000000000000000 R13: 0x0000000000000002
      RDX: 0x0000555922fb53d8 R9:  0x0000000000000000 R14: 0x00007f91973fc530
      RSI: 0x00005559241f2450 R10: 0x00007f91809c7690 R15: 0x0000000000000000
      SP:  0x00007f918effc340

*** END ***

The skrouterd stack frames decode as:

# addr2line -e $XYZ/usr/sbin/skrouterd 0x507d8
/build/src/adaptors/http2/http2_adaptor.c:2961

# addr2line -e $XYZ/usr/sbin/skrouterd 0xc19cc
/build/src/server.c:802

# addr2line -e $XYZ/usr/sbin/skrouterd 0xc95a6
/build/src/server.c:1108

Using the given git sha (see VERSION above), the crash corresponds to this line in the code:

https://github.com/skupperproject/skupper-router/blob/be3a1abb724c5763e225e4a667138e2e4b829832/src/adaptors/http2/http2_adaptor.c#L2961

    case PN_RAW_CONNECTION_DISCONNECTED: {
        -> qd_set_condition_on_vflow(conn->pn_raw_conn, conn->vflow);

Looking at the objdump -S disassembly of the /usr/sbin/skrouterd image, the faulting instruction is:

 ->507d8: 49 8b 74 24 20       mov    0x20(%r12),%rsi
   507dd: 49 8b 7c 24 18       mov    0x18(%r12),%rdi
   507e2: e8 b9 d1 fd ff       call   2d9a0 <qd_set_condition_on_vflow>

Which is prior to the qd_set_condition_on_vflow() call.  From the stack frame, r12 is zero:
    Registers:
      RAX: 0x0000555922ef87d8 RDI: 0x00007f91809c7420 R11: 0x00007f9180000020
      RBX: 0x00005559241f2450 RBP: 0x00007f918effbf50 R12: 0x0000000000000000
      RCX: 0x00005559242a6c90 R8:  0x0000000000000000 R13: 0x0000000000000000
      RDX: 0x0000555922fb53d8 R9:  0x0000000000000000 R14: 0x00007f91809c7420
      RSI: 0x00005559241f2450 R10: 0x00007f91809c7690 R15: 0x00005559241f2450
      SP:  0x00007f918effbe80

So my guess is that the conn pointer is in r12 and it is null. Can't explain how that could happen.

Do not have a reproducer, though at the time the connector to a grpc-based server was flapping (going up then down rapidly).

**Comment by ganeshmurthy** [comment]
Fixed via https://github.com/skupperproject/skupper-router/issues/1424
