### ISSUE TITLE
[QUESTION] Max connections to another router

### ISSUE THREAD

**Issue by tom342178** [skupperproject/skupper-router#1149]
What are the limitation on the max connections to other skupprt-routers? Is it max file descriptors? ~4096

**Comment by ganeshmurthy** [comment]
Say there are two `interior` routers, Router A and Router B, in your router network, you usually define just one connector between the two routers like this - 

RouterB.conf
```
connector {
    name: connectorToA
    saslMechanisms: ANONYMOUS
    host: <host-name>
    role: inter-router
    port: <port-number>
}
```
Connectors enable bidirectional traffic between interior routers and need to be defined only in one router.

In the router entity, there is an attribute called `dataConnectionCount`
https://github.com/skupperproject/skupper-router/blob/2.4.x/python/skupper_router/management/skrouter.json#L597
which you can use to specify the number of parallel connections that will be created by this single connector that will stream data between routers. The `dataConnectionCount` is defaulted optimally based on the workerThreads assigned to the router as seen here - https://github.com/skupperproject/skupper-router/blob/2.4.x/src/connection_manager.c#L767 
The router has been shown to perform well with the default value for `dataConnectionCount` and you should make minor tweaks to it after incrementally testing using your application workloads.

To ask questions, you can use the "Mailing List" link at the bottom of this page - [Mailing list](https://groups.google.com/forum/#!forum/skupper)

**Comment by ganeshmurthy** [comment]
I am  closing this issue. Again, please ask questions in the [Mailing list](https://groups.google.com/forum/#!forum/skupper)
