### ISSUE TITLE
TCP adaptor listener connections hang if no connectors are defined

### ISSUE THREAD

**Issue by ganeshmurthy** [skupperproject/skupper-router#120]
If a connector is not defined but a listener is defined:

    A client connects to the listener. Listener starts with SYN, SYN/ACK, ACK.
    The client sends the first payload bytes
    No further traffic is passed on the client connection
    Even if the server is started while the client is waiting no further traffic is passed on to the client.
    The client seems to hang

If there is no address in the address table, close the client connection. Also free all the connection related resources in the skupper-router.

**Comment by kgiusti** [comment]
This is caused because the tcp listener is waiting for credit to arrive.  Since credit is only available when tcpConnectors are provisioned the client will hang until the tcpConnector is provisioned.
