### ISSUE TITLE
Remove the use of pip install to install the skupper-router python modules. 

### ISSUE THREAD

**Issue by ganeshmurthy** [skupperproject/skupper-router#1305]
Instead just copy these modules into the install folder and modify PYTHONPATH to point to the appropriate folders

**Comment by jiridanek** [comment]
@kgiusti It seems that RHEL 7 compatibility is not required. Therefore, if we base the RPM build on python3.11, which is available on RHEL/CentOS 8+, we will have sufficiently new setuptools which understands `pyproject.toml` and then the build issues should go away.

Wdyt? Is it worth a try?
