### ISSUE TITLE
DockerResponseServerError { status_code: 500, message: "container create failed (no logs from conmon): conmon bytes \"\": readObjectStart: expect { or n, but found \0, error found in #0 byte o

### ISSUE THREAD

**Issue by jiridanek** [skupperproject/skupper-router#1324]
```
DockerResponseServerError { status_code: 500, message: "container create failed (no logs from conmon): conmon bytes \"\": readObjectStart: expect { or n, but found \0, error found in #0 byte of ...||..., bigger context ...||..." }
stack backtrace:
```

This seems to be caused by an update of podman or one of its dependencies

* Unpacking crun (101:1.12-0ubuntu22.04+obs65.5) over (0.17+dfsg-1.1) ... -> Unpacking crun (101:1.12-0ubuntu22.04+obs65.13) over (0.17+dfsg-1.1) ...
* Unpacking containers-common (4:1-0ubuntu22.04+obs20.52) ... -> Unpacking containers-common (4:1-0ubuntu22.04+obs20.56) ...
* Setting up conmon (2:2.1.8-0ubuntu22.04+obs16.33) ... -> Setting up conmon (2:2.1.9-0ubuntu22.04+obs17.1) ...
* Setting up crun (101:1.12-0ubuntu22.04+obs65.5) ... -> Setting up crun (101:1.12-0ubuntu22.04+obs65.13) ...
* Setting up containers-common (4:1-0ubuntu22.04+obs20.52) ... -> Setting up containers-common (4:1-0ubuntu22.04+obs20.56) ...

Version of podman itself between last successful and a series of failures has not changed

* Setting up podman (4:4.6.2-0ubuntu22.04+obs81.12) ...

**Comment by jiridanek** [comment]
https://github.com/skupperproject/skupper-router/actions/runs/7251189221/job/19753018142#step:8:80

**Comment by jiridanek** [comment]
This seems to be caused by the conmon upgrade, according to

* https://github.com/containers/podman/issues/21024

**Comment by XaratosS** [comment]
So is there a fix for it?

**Comment by jiridanek** [comment]
@XaratosS using podman installed from linuxbrew was the fix for me at that time. What version of podman you use, where is that from, and what are your troubles? Ubuntu 24.04 has podman 4.9.3, so maybe if you need this for Github Actions, that version of podman may work well enough without the need to install anything newer

**Comment by jiridanek** [comment]
There should not be any problems with Docker, as far as I know. It's just that we tend to prefer podman for CI.

**Comment by XaratosS** [comment]
Hmmn then it might be a diffrent issue. Maybe I havent set up the right permissions for the token.

**Comment by XaratosS** [comment]
Sadly the issue is still persistent: 

```
Error: container create failed (no logs from conmon): conmon bytes "": readObjectStart: expect { or n, but found , error found in #0 byte of ...||..., bigger context ...||...
```

Docker Version: 
```
docker version
Client: Docker Engine - Community
 Version:           26.1.3
 API version:       1.45
 Go version:        go1.21.10
 Git commit:        b72abbb
 Built:             Thu May 16 08:33:42 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          26.1.3
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.10
  Git commit:       8e96db1
  Built:            Thu May 16 08:33:42 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.32
  GitCommit:        8b3b7ca2e5ce38e8f31a34f35b2b68ceb8470d89
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by jiridanek** [comment]
@XaratosS are you even using skupper at all? or did you just google for a docker error message and found the issue here?

**Comment by XaratosS** [comment]
@jiridanek I figured out the error. I had to switch versions. 24.6.0 was not working on Docker. I had to go down to 24.3.1. This one worked fine. I remembered it later on. Sorry for all the work I put you through.

**Comment by jiridanek** [comment]
> 24.6.0 was not working on Docker. I had to go down to 24.3.1.

@XaratosS these are versions of _what_, exactly?

**Comment by XaratosS** [comment]
Oh yeah I was talking about awx. I think I am defenetly in the wrong project...
