### ISSUE TITLE
skupper-router Image configure.sh unbound variable

### ISSUE THREAD

**Issue by ajssmith** [skupperproject/skupper-router#133]
/home/qdrouterd/bin/configure.sh: line 63: QDROUTERD_AUTO_CREATE_SASLDB_SOURCE: unbound variable

**Comment by fgiorgetti** [comment]
Need to add default, empty values in case those variables are not set.

**Comment by jiridanek** [comment]
`if [[ -n "${QDROUTERD_AUTO_CREATE_SASLDB_SOURCE:-}" ]]; then`
