### ISSUE TITLE
arm64 SIGSEGV, Segmentation fault. 0x0000fffff7251848 in access_mem () from /lib64/libunwind.so.8

### ISSUE THREAD

**Issue by jiridanek** [skupperproject/skupper-router#1362]
```
+ gdb -quiet -iex 'set pagination off' -iex 'set debuginfod enabled on' -ex run -ex 'thread apply all bt' -ex 'quit $_exitcode' --batch --args redhat-linux-build/tests/cpp/cpp_unit/cpp_unit
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Stubbing doesn't work. Define QD_REQUIRE_STUBBING_WORKS to get an abort()

Program received signal SIGSEGV, Segmentation fault.
0x0000fffff7251848 in access_mem () from /lib64/libunwind.so.8

Thread 1 (Thread 0xfffff7fea020 (LWP 4523) "cpp_unit"):
#0  0x0000fffff7251848 in access_mem () from /lib64/libunwind.so.8
#1  0x0000fffff7257944 [PAC] in _ULaarch64_step () from /lib64/libunwind.so.8
#2  0x0000fffff7257cf0 [PAC] in _ULaarch64_tdep_trace () from /lib64/libunwind.so.8
#3  0x0000fffff7258000 [PAC] in unw_backtrace () from /lib64/libunwind.so.8
#4  0x0000aaaaaaae634c [PAC] in test_backtrace::b_stores_backtrace (item=...) at /builddir/build/BUILD/skupper-router-2.5.0/tests/cpp/cpp_unit/test_alloc_pool.cpp:50
#5  0x0000aaaaaaae6378 [PAC] in test_backtrace::a_calls_b (item=...) at /builddir/build/BUILD/skupper-router-2.5.0/tests/cpp/cpp_unit/test_alloc_pool.cpp:55
#6  0x0000aaaaaaae639c in test_backtrace::DOCTEST_ANON_FUNC_4 () at /builddir/build/BUILD/skupper-router-2.5.0/tests/cpp/cpp_unit/test_alloc_pool.cpp:80
#7  0x0000aaaaaaaed174 [PAC] in doctest::Context::run (this=this@entry=0xffffffffea78) at /builddir/build/BUILD/skupper-router-2.5.0/tests/cpp/helpers/../doctest/doctest.h:7007
#8  0x0000aaaaaaad2088 [PAC] in main (argc=1, argv=0xffffffffebf8) at /builddir/build/BUILD/skupper-router-2.5.0/tests/cpp/helpers/c_unittests_main.cpp:76
Value can't be converted to integer.
error: Bad exit status from /var/tmp/rpm-tmp.BZwcfD (%check)
    Bad exit status from /var/tmp/rpm-tmp.BZwcfD (%check)
```

**Comment by jiridanek** [comment]
This happens if you link in libunwind. It replaces the glibc `backtrace` implementation with its own

> libunwind provides a weak symbol backtrace so that the glibc one gets redirected to unw_backtrace?

https://github.com/gperftools/gperftools/issues/1277#issuecomment-879225775

**Comment by jiridanek** [comment]
Here's libunwind ticket for this
* https://github.com/libunwind/libunwind/issues/260

**Comment by jiridanek** [comment]
I've only seen it crash in cpp_unit tests, when backtrace() is called. Because libunwind replaces the glibc function backtrace() when libunwind is present on linker path.

I imagine this will also affect the signal handler that Ken created. So if you crash the router, then it will crash again trying to use libunwind to print crash backtrace.

**Comment by jiridanek** [comment]
@ganeshmurthy This will be fixed when you do the 1.8 libunwind upgrade in your PR.

**Comment by ganeshmurthy** [comment]
> @ganeshmurthy This will be fixed when you do the 1.8 libunwind upgrade in your PR.

The compilation of libunwind has run into a problem - 
https://github.com/skupperproject/skupper-router/actions/runs/7831625355/job/21383300937?pr=1403#step:3:1626

We might have to exclude libunwind from the arm image

**Comment by jiridanek** [comment]
> The compilation of libunwind has run into a problem -
> https://github.com/skupperproject/skupper-router/actions/runs/7831625355/job/21383300937?pr=1403#step:3:1626

* @ganeshmurthy yeah, been there, reported that https://github.com/libunwind/libunwind/issues/693 ;p

**Comment by ganeshmurthy** [comment]
> * @ganeshmurthy yeah, been there, reported that

Ah ok. This comment [1] talks about compiling on Fedora but we are compiling on Debian 
In any case, I am working on a fix to the PR that will conditionally omit building libunwind for an arm64 build

[1] https://github.com/libunwind/libunwind/issues/693#issuecomment-1874568063
