### ISSUE TITLE
Build and release arm64/v2 (aarch64) skupper-router docker image

### ISSUE THREAD

**Issue by jiridanek** [skupperproject/skupper-router#1367]
This is to support

* https://github.com/skupperproject/skupper/pull/1064

## Plan

There are some implementation suggestions in the original PR

* https://github.com/skupperproject/skupper-router/pull/1100

and also @ganeshmurthy has a write-up discussing options.

In summary, we need to eventually produce multiarch manifest, but it's ok to not have it initially (and give the aarch64 image a different name, and then manually specify that when initializing skupper). We want the build to be reasonably fast (so qemu-user is out, or at least running everything in qemu-user is out). There should be two solutions, both crosscompilation and a native build. Crosscompilation is useful on GitHub Actions, and native build can be done on Travis CI or in general by those who have physical arm64 machines, such as inside Red Hat.

**Comment by ganeshmurthy** [comment]
This has been resolved via https://github.com/skupperproject/skupper-router/issues/1404
