### ISSUE TITLE
It seems like the 2.4.0-rc1 image tag was deleted

### ISSUE THREAD

**Issue by iagodvsantos** [skupperproject/skupper-router#1395]
Last night our skupper-routers started crashing and we could no longer pull the `quay.io/skupper/skupper-router:2.4.0-rc1` tag image.

**Comment by ganeshmurthy** [comment]
On Mon, Feb 5, 2024 at 7:34 AM Iago David ***@***.***> wrote:

> Last night our skupper-routers started crashing and we could no longer
> pull the quay.io/skupper/skupper-router:2.4.0-rc1 tag image.
>
Could you pull the 2.4.0 tag image ?
