### ISSUE TITLE
Need support for tcpConnection management entity in new tcplite adaptor

### ISSUE THREAD

**Issue by kgiusti** [skupperproject/skupper-router#1402]
For feature parity with legacy tcp adaptor.
See #1401

**Comment by kgiusti** [comment]
Need to also add CI tests for validating the management entity behavior once both adaptors support it.

**Comment by kgiusti** [comment]
Or... deprecate the tcpConnection mgmt entity altogether - maybe use flow records instead?
Opinions?

**Comment by ganeshmurthy** [comment]
We are removing this feature from the tcp lite adaptor. I am closing this issue.
