### ISSUE TITLE
Github Actions CI test fail due to sanitizer crashes

### ISSUE THREAD

**Issue by kgiusti** [skupperproject/skupper-router#1444]
The problem is due to a change in the address randomization configuration of the underlying Ubuntu hosts.  See https://github.com/actions/runner-images/issues/9491

Using the work-arounds described in the above issue it will be possible to run the sanitizers on the Ubuntu-os builds only. The containerized fedora/centos builds will not be able to run the sanitizers since there is (apparently) no way to modify the vm.mmap_rnd_bits setting via sysctl. I've tried 
```
sysctl -w rm.mmap_rnd_bits=28
```
both from within the container itself (not allowed) and also via the --sysctl option passed to docker when creating the container (again, not allowed):

```
$ sysctl -w vm.mmap_rnd_bits=28
sysctl: setting key "vm.mmap_rnd_bits": Read-only file system
```

```
  /usr/bin/docker create --name <blab-blabbity-blab>
  invalid argument "vm.mmap_rnd_bits=28" for "--sysctl" flag: sysctl 'vm.mmap_rnd_bits=28' is not allowed
  See 'docker create --help'.
```

**Comment by jiridanek** [comment]
```
sysctl: setting key "vm.mmap_rnd_bits": Read-only file system
```

Can you mount /proc read-write from host when configuring docker? Let's leave the thought here in case some hapless internet surfer finds it here.
