### ISSUE TITLE
Centos 8 has reached EOL.  Migrate CI test to a supported version of centos stream.

### ISSUE THREAD

**Issue by kgiusti** [skupperproject/skupper-router#1517]
https://blog.centos.org/2023/04/end-dates-are-coming-for-centos-stream-8-and-centos-linux-7/

**Comment by jiridanek** [comment]
@adelton suggests switching to Alma Linux if there is still need to support Rhel 8 downstream in the future.

**Comment by kgiusti** [comment]
Good to know about Alma. At today's scrum people didn't see a need to stick with 8 for the foreseeable future.

**Comment by jiridanek** [comment]
Ok that resolves that!
