### ISSUE TITLE
ctest warns of multiple leaks of /home/kgiusti/work/skupper/skupper-router/BUILD/tests/next_port.lock

### ISSUE THREAD

**Issue by kgiusti** [skupperproject/skupper-router#155]
Looks like system_test:QdManager class instantiates a dummy Tester(), which results in the leak.
IIUC this dummy Tester really isn't necessary - QdManager should probably call subprocess.popen directly (like 'run_cur()' in the same file).

Error message:

```
41: test_verify_inter_router_presettled_count_DISPATCH_1540 (system_tests_delivery_counts.TwoRouterLargeMessagePresettledCountTest) ... /home/kgi\
usti/work/skupper/skupper-router/tests/system_tests_delivery_counts.py:346: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/kgiusti\
/work/skupper/skupper-router/BUILD/tests/next_port.lock' mode='a+t' encoding='UTF-8'>                                                             
41:   if has_mobile_dest_in_address_table(self.sender_addr, self.dest):                                                                           
41: ResourceWarning: Enable tracemalloc to get the object allocation traceback                                                                    
41: /home/kgiusti/work/skupper/skupper-router/tests/system_tests_delivery_counts.py:335: ResourceWarning: unclosed file <_io.TextIOWrapper name='\
/home/kgiusti/work/skupper/skupper-router/BUILD/tests/next_port.lock' mode='a+t' encoding='UTF-8'>                                                
41:   self.links = get_inter_router_links(self.receiver_addr)                                                                                     
41: ResourceWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by jiridanek** [comment]
My first thought was to implement content manager in QdManager, so we can change

```
qdm = QdManager(address=address)
```

into

```
with QdManager(address=address) as qdm:
    ....
```

Or wrap it in https://docs.python.org/3/library/contextlib.html#contextlib.closing

**Comment by kgiusti** [comment]
> My first thought was to implement content manager in QdManager, so we can change
> 
> ```
> qdm = QdManager(address=address)
> ```
> 
> into
> 
> ```
> with QdManager(address=address) as qdm:
>     ....
> ```
> 
> Or wrap it in https://docs.python.org/3/library/contextlib.html#contextlib.closing

That would certainly fix it, but I've just looked at the 55+ uses of it in the tests and I'm WAY too lazy to refactor them to use a context!

**Comment by jiridanek** [comment]
> That would certainly fix it, but I've just looked at the 55+ uses of it in the tests and I'm WAY too lazy to refactor them to use a context!

You still had to delete `self, ` 55+ times. :D
