### ISSUE TITLE
skupper-router image 'qdstat -g'  or 'qdstat --all-entities' errors

### ISSUE THREAD

**Issue by ajssmith** [skupperproject/skupper-router#167]
Running qdstat 1.18.0 against skupper-router image 

-g returns AttributeError:
--all-entities returns BadRequestStatus: No such entity type 'org.apache.qpid.dispatch.router.config.linkRoute'

Is this highlighting the need for new skstat and skmanage?

**Comment by jiridanek** [comment]
> --all-entities returns BadRequestStatus: No such entity type 'org.apache.qpid.dispatch.router.config.linkRoute'

That one sure looks like it, `skrouterd` does not recognize `org.apache.qpid.dispatch.router.config.linkRoute` because it was removed in #57, but `qdstat` asks for it.

**Comment by ted-ross** [comment]
I don't believe it is a requirement for the 1.18 qdstat to be compatible with skupper-router.  The skupper-router qdstat does not exhibit this problem.
