### ISSUE TITLE
system_tests_tcp_adaptor: TCP_TEST TCP_Adaptor test setup failed. Echo tests never executed.

### ISSUE THREAD

**Issue by jiridanek** [skupperproject/skupper-router#205]
This has appeared multiple times, recently. Looks like timeout in test setup(?).

https://github.com/jiridanek/skupper-router/runs/5598008468?check_suite_focus=true#step:26:2024

```
59:             if poll_loops == 0:
59: >               assert False, "TCP_TEST TCP_Adaptor test setup failed. Echo tests never executed."
59: E               AssertionError: TCP_TEST TCP_Adaptor test setup failed. Echo tests never executed.
59: E               assert False
```

**Comment by jiridanek** [comment]
https://github.com/skupperproject/skupper-router/runs/5691219111?check_suite_focus=true#step:26:11010, failed to upload logs, same as the previous failure

**Comment by ganeshmurthy** [comment]
Don't see this anymore, closing
