### ISSUE TITLE
Remove Non-linux build targets in travis CI

### ISSUE THREAD

**Issue by kgiusti** [skupperproject/skupper-router#24]
osx

**Comment by jiridanek** [comment]
Travis CI is now paid. Only s390x and arm are free. Travis calls that the Partner queue.

https://docs.travis-ci.com/user/billing-overview/#usage---credits

IMO we need to

# remove all builds except aarch64 and s390x
# activate travis ci for this repo

**Comment by jiridanek** [comment]
> To run a job using Partner Queue Solution, use the following .travis.yml tags in your public repository:

```
os: linux
arch:
  - arm64
  - ppc64le
  - s390x
```

Does that mean that we have to use exactly these arches, or we can use subset and still be on the free queue?

**Comment by jiridanek** [comment]
@ted-ross I wrote to TravisCI support regarding the arm64 and s390x arches:

## My ticket

> Hello, I've been using TravisCi for a long time now. After your pricing change I twice asked for and was granted OSS credits for some of my projects.

> I am seeking to run arm64 builds for the project linked below (github/jiridanek/skupper-router). According to your docs, these should fall into the free Partner Queue [1] so they should not consume credits. However, the Travis page says "Builds have been temporarily disabled for private and public repositories due to a negative credit balance. Please go to the Plan page to replenish your credit balance."

> How can I resolve this so I can run the free builds?

## Reply

> Thank you for reaching out! I will happily assist you.

> To be able to trigger partner queue solution builds you will need at least 1 credit within your account. However, you had a negative credits balance. I have added an additional 500 to your build credits that will enable it.

> If you need further assistance, we will be glad to help.

**Comment by jiridanek** [comment]
@ted-ross I think that this means it should be possible to enable TravisCI for the skupperproject GH organization and have free builds for these arches (as long as we never exhaust the initial free credits on nonfree jobs). Therefore, I think that the linked PR #38 should be merged, and then TravisCI can be enabled.
