### ISSUE TITLE
13: ::PolicyHostAddrTest::test_policy_hostaddr_ipv6 SKIPPED (System IPv6...)

### ISSUE THREAD

**Issue by jiridanek** [skupperproject/skupper-router#375]
https://github.com/skupperproject/skupper-router/runs/6140819152?check_suite_focus=true#step:26:485

```
13: ::PolicyHostAddrTest::test_policy_hostaddr_ipv6 SKIPPED (System IPv6...)
13: ::PolicyHostAddrTest::test_policy_hostaddr_ipv6_wildcard SKIPPED (Sy...)
```

```
13: ::PolicyHostAddrTest::test_policy_malformed_hostaddr_ipv6 SKIPPED (S...)
```

IPv6 tests should not be skipped in CI.

**Comment by jiridanek** [comment]
GitHub Actions don't configure IPv6. Maybe we can have it in container? Somehow get it at least for loopback? https://github.com/actions/virtual-environments/issues/668

**Comment by jiridanek** [comment]
I am inclined to leave this unresolved. The ipv6 test runs on the Ubuntu jobs outside docker. I am not sure how to enable it in GHA-managed docker.

**Comment by kgiusti** [comment]
Reopening to track corresponding PR
