### ISSUE TITLE
system_tests_user_id, system_tests_http2_tls become more flaky with LTO enabled

### ISSUE THREAD

**Issue by jiridanek** [skupperproject/skupper-router#396]
https://github.com/skupperproject/skupper-router/runs/6224186833?check_suite_focus=true

LTO is enabled as an attempt to workaround https://github.com/skupperproject/skupper-router/issues/344

Could be that some timing is different and existing problems in the code are more likely to manifest. Other explanations are possible. The skupper-router image is on LTO for some time already, and there were no complaints as far as I noticed. On the other hand, it is possible problems simply were not noticed, or were dismissed with other explanations.

Maybe the time is not yet ripe for enabling LTO and the prudent choice is to back off.

**Comment by jiridanek** [comment]
This might've been fixed as part of tls test improvements. What's your opinion on having LTS enabled in the CI?

**Comment by jiridanek** [comment]
Not fixed, sometimes happens without LTO, https://github.com/skupperproject/skupper-router/actions/runs/3384376063/jobs/5621267808#step:28:853

**Comment by ganeshmurthy** [comment]
Not seen this issue in about 2 years, closing
