### ISSUE TITLE
Flaky failure in c-benchmarks: `what():  Failed to connect in time`

### ISSUE THREAD

**Issue by jiridanek** [skupperproject/skupper-router#402]
https://github.com/skupperproject/skupper-router/runs/6239120583?check_suite_focus=true#step:9:3138

```
65: BM_TCPEchoServerLatency1QDRThread           3.13 ms        0.013 ms           10
65: terminate called after throwing an instance of 'std::runtime_error'
65:   what():  Failed to connect in time
```

This happened on CentOS 8 as flaky failure after enabling IPv6 on lo. This may be just a coincidence.

**Comment by jiridanek** [comment]
https://en.wikipedia.org/wiki/Mokusatsu

**Comment by ganeshmurthy** [comment]
Closing this for now
