### ISSUE TITLE
Use SIGABRT to kill stuck `skrouterd`, to get backtrace where it was stuck

### ISSUE THREAD

**Issue by jiridanek** [skupperproject/skupper-router#517]
### Discussed in https://github.com/skupperproject/skupper-router/discussions/465

<div type='discussions-op-text'>

<sup>Originally posted by **jiridanek** May 10, 2022</sup>
Currently tests kill with sigkill. I am wondering if sigabrt would not be more appropriate.

https://github.com/skupperproject/skupper-router/blob/3111aaf6269c893c20f3fef5071f55c2899e0a97/tests/system_test.py#L378-L407</div>

**Comment by kgiusti** [comment]
merged to 2.0.2
