### ISSUE TITLE
Various leaks of `pn_buffer` and other Proton types in tests system_tests_open_properties and system_tests_http1_adaptor

### ISSUE THREAD

**Issue by jiridanek** [skupperproject/skupper-router#540]
https://github.com/skupperproject/skupper-router/runs/6639279150?#step:27:1180
```
53: -----------------------------------------------------
53: Suppressions used:
53:   count      bytes template
53:       1         56 ^load_server_config$
53:       1        288 ^pni_data_grow$
53:       2         96 ^pn_buffer$
53: -----------------------------------------------------
```
https://github.com/skupperproject/skupper-router/runs/6639279150?#step:27:1661
```
53: -----------------------------------------------------
53: Suppressions used:
53:   count      bytes template
53:       1         56 ^load_server_config$
53:       1       4608 ^pni_data_grow$
53:       1         32 ^pn_buffer$
53:       1        256 ^pn_buffer_ensure$
53: -----------------------------------------------------
```
https://github.com/skupperproject/skupper-router/runs/6639279150?#step:27:2443
```
57: Router TestBadEndpoints output file:
57: >>>>
57: -----------------------------------------------------
57: Suppressions used:
57:   count      bytes template
57:       1         64 ^pgetaddrinfo$
57: -----------------------------------------------------
```

> yep, those look like real leaks, but I was mainly concerned that the pn_raw_connection leaks had gone now - I can also think about those leaks too
> they are related to pn_data and not cleaning that up

**Comment by kgiusti** [comment]
The pgetaddrinfo leak appears to be a proactor cleanup bug.  See https://issues.apache.org/jira/browse/PROTON-2568

**Comment by ganeshmurthy** [comment]
> The pgetaddrinfo leak appears to be a proactor cleanup bug. See https://issues.apache.org/jira/browse/PROTON-2568

PROTON-2568 has been released, closing
