### ISSUE TITLE
HTTP/2: high cpu utilization when connected to nginx

### ISSUE THREAD

**Issue by kgiusti** [skupperproject/skupper-router#582]
This is an invalid configuration I believe, but the behavior is unexpected and doesn't appear to resolve:

To reproduce:

- start a router with default config
- skmanage create --type httpListener port=8000 protocolVersion=HTTP2 address=http2_service
- skmanage create --type httpConnector host=127.0.0.1 port=8800 protocolVersion=HTTP2 address=http2_service
- start an nginx server listening on port 8800 (content irrelevant - never used)
- wait for nginx server to connect
- observe cpu utilization
- stop the nginx server; note that cpu utilization is still very high.

**Comment by kgiusti** [comment]
Utilization returns to normal after nginx is stopped - I cannot reproduce the persistent CPU utilization I observed before.

However while the nginx server is present the router spins connecting and reconnecting, forcing the CPU to 100%.

**Comment by kgiusti** [comment]
Analysis: when the connection to the nginx server fails, the http2 adaptor schedules a 2 second pause before reconnecting.  However, the core immediately tries to reactivate the connection and reschedules the activation time with zero delay.  This causes an immediate re-connection to the server and the process resumes again.

**Comment by ganeshmurthy** [comment]
> Analysis: when the connection to the nginx server fails, the http2 adaptor schedules a 2 second pause before reconnecting. However, the core immediately tries to reactivate the connection and reschedules the activation time with zero delay. This causes an immediate re-connection to the server and the process resumes again.

This is a bug. The router should not immediately try to re-connect to the server. It should wait for 2 seconds.

**Comment by kgiusti** [comment]
> > Analysis: when the connection to the nginx server fails, the http2 adaptor schedules a 2 second pause before reconnecting. However, the core immediately tries to reactivate the connection and reschedules the activation time with zero delay. This causes an immediate re-connection to the server and the process resumes again.
> 
> This is a bug. The router should not immediately try to re-connect to the server. It should wait for 2 seconds.

Yeah, I've hacked together a simple-minded fix: use a flag to prevent the core from re-activating the connection when the re-connect timer is running. I'll post a PR for you to review shortly.

**Comment by kgiusti** [comment]
@ganeshmurthy see the linked PR. I'm not exactly loving that fix - you can probably come up with something cleaner.
