### ISSUE TITLE
Make CI builds (especially skupper-router image) more production-like

### ISSUE THREAD

**Issue by jiridanek** [skupperproject/skupper-router#60]
This is a follow up to (my) comments on https://github.com/skupperproject/skupper-router/pull/44. This ticket suggests to consider doing (and eventually do) one or more of the following

* [x] base the skupper-router image on CentOS Stream 8 or UBI 8 https://github.com/skupperproject/skupper-router/pull/84
* [x] build the router with production-like flags, such as the various flavors of `-fstack-protector` and with `-D_FORTIFY_SOURCE=2`
   * [x] https://github.com/skupperproject/skupper-router/issues/444
* [ ] use RPM .spec file to build the router in the builder image and then install it from that RPM in the deployed image
   * [x] https://github.com/skupperproject/skupper-router/issues/186
   * [x] WON'T DO, the production image is not using rpm either
* [x] build qpid-proton as a static library and link it into dispatch; possibly use `-DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON` and `-fno-semantic-interposition` (https://fedoraproject.org/wiki/Changes/PythonNoSemanticInterpositionSpeedup)
   * https://github.com/skupperproject/skupper-router/pull/96
* use catchsegv or `-lSegFault` in production build to always dump stacktrace on crash (use `addr2line` to later decrypt the trace)
* `LIBC_FATAL_STDERR_=1`
* why our libwebsockets is built with `LWS_WITH_LIBUV=ON` and `LWS_WITH_HTTP2=OFF`?
   * [x] fixed by @ajssmith in https://github.com/skupperproject/skupper-router/pull/369
* `set -Eeuo pipefail`
* `QDROUTERD_AUTO_MESH_DISCOVERY` as core skupper-router feature, instead of hacky config file editing during image startup
* some tests for the container image, to be reasonably sure Skupper was not broken by changes
   * [ ] https://github.com/skupperproject/skupper-router/pull/169
   * [x] https://github.com/skupperproject/skupper-router/pull/381

**Comment by ganeshmurthy** [comment]
Most tasks completed
