### ISSUE TITLE
system_tests_http2_tls failing Http2TlsAuthenticatePeerOneRouter.test_head_request

### ISSUE THREAD

**Issue by ganeshmurthy** [skupperproject/skupper-router#603]
```
60: ======================================================================
60: FAIL: test_head_request (system_tests_http2_tls.Http2TlsAuthenticatePeerOneRouter)
60: ----------------------------------------------------------------------
60: Traceback (most recent call last):
60:   File "/home/tross/git/ted-ross/skupper-router/tests/system_tests_http2_tls.py", line 568, in test_head_request
60:     self.router_qdra.wait_log_message(error_log)
60:   File "/home/tross/git/ted-ross/skupper-router/tests/system_test.py", line 817, in wait_log_message
60:     assert retry(lambda: _is_pattern_present(router_log), **retry_kwargs),\
60: AssertionError: 'SSL routines:tls_process_client_certificate:peer did not return a certificate' not present in router log
60:
60: ----------------------------------------------------------------------
60: Ran 65 tests in 124.349s
60:
60: FAILED (failures=1)
```

**Comment by ted-ross** [comment]
The following line does appear in the log file:

```2022-07-12 16:34:45.067285 -0400 PROTOCOL (error) [C0] conn->ingress=1, Error processing TLS: error:0A0000C7:SSL routines::peer did not return a certificate (.../skupper-router/src/adaptors/http2/http2_adaptor.c:2398)```

**Comment by ganeshmurthy** [comment]
I am on F35 and I see the following line in the log -
```
SSL routines:tls_process_client_certificate:peer did not return a certificate'
```
and the test is looking for the above line and hence it passes.

@ted-ross is on F36 and is seeing - 
```
SSL routines::peer did not return a certificate
```

@ted-ross can you please get the latest proton and re-try the test ? 

The simple fix to this would be to modify the test to look for ```peer did not return a certificate``` but I want to talk to @cliffjansen to get his thoughts.

**Comment by ganeshmurthy** [comment]
@ted-ross thanks for testing. I have alerted @cliffjansen via email.

**Comment by cliffjansen** [comment]
OpenSSL has changed.

Fedora 35 uses openssl 1.X while Fedora 36 uses 3.X.

The old error format before openssl 3.X:

  error:[error code]:[library name]:[function name]:[reason string]

New error format:

  error:[error code]:[library name]::[reason string]

That appears to reflect an internal code reorganization that made the "function name" part no longer feasible or desirable.  So it is now empty but they have kept the same number of colons, presumably provide some backwards compatibility for programs that parsed based on those colons.

Proton just passes back the OS-specific library's main error string whether it is OpenSSL or SChannel.

It is possible that skupper-router an get by with just the last portion ("reason string"), and that would be compatible with all versions of OpenSSL to date.

**Comment by ganeshmurthy** [comment]
@cliffjansen thanks for the explanation. I will raise a test change PR where the test is looking only for the last portion of the error message (reason string).

**Comment by ganeshmurthy** [comment]
This has been fixed via https://github.com/skupperproject/skupper-router/commit/e3f52d1f870e166bd0cf8ebacac2fd32fac9caf6
