### ISSUE TITLE
HTTP1 adaptor very occasionally fails to delete connection associated with connector

### ISSUE THREAD

**Issue by kgiusti** [skupperproject/skupper-router#627]
This seems to be a race where the server has dropped the connection at the same moment that the httpConnector is deleted my management:

https://github.com/skupperproject/skupper-router/runs/7430660343?check_suite_focus=true#step:28:2542

When the server drops, the http1 adaptor attempts to re-establish the connection. During the time while the re-connect is in flight if the corresponding httpConnector is deleted then the qdr_connection_t (and associated links) are not torn down.  This leaves a "phantom" service available that cannot be deleted.

**Comment by kgiusti** [comment]
1) server disconnects - PN_RAW_CONNECTION_DISCONNECTED
2) http adapter initiates reconnect (pn_proactor_raw_connect() via timer (QD_CONN_ADMIN_ENABLED==T)
3) mgmt invokes qd_http1_delete_connector, sets QD_CONN_ADMIN_ENABLED=F, call qdr_core_close_connection(qdr_conn)
4) core activates http connection by wakes pn_conn
5) raw connect fails, http adaptor gets PN_RAW_CONNECTION_DISCONNECTED (no server)
   - ADMIN is disabled so no attempt to reconnect (OK)
6) PN_RAW_CONNECTION_WAKE is never generated since pn_conn is disconnected
   - qdr_connection_process() is never run
     - qdr_http1_server_core_conn_close() never called
       - links and connection never closed

**Comment by jiridanek** [comment]
Any possible relation to https://github.com/skupperproject/skupper-router/issues/612? (Not that I really know of any, just asking.)

**Comment by kgiusti** [comment]
Hit again: failure in Http1AdaptorListenerConnectTest::test_02_listener_interior. The connector is deleted by mgmt, but the connection cleanup never triggers.

https://github.com/skupperproject/skupper-router/runs/7528026524?check_suite_focus=true#step:29:2461
