### ISSUE TITLE
GHA CI failures: [error] Process completed with exit code 137.

### ISSUE THREAD

**Issue by kgiusti** [skupperproject/skupper-router#634]
https://github.com/skupperproject/skupper-router/runs/7508068051?check_suite_focus=true#step:28:1535

This failure has appeared in the last week. Best I can tell from googling the above error message is that the CI container is being OOMed. There's very little information available to debug this.

Unclear if this is caused by an issue with the router - memory leak? - or if something in the GHA CI has changed recently.

**Comment by jiridanek** [comment]
I think this is ecode from CTest process itself, not from Docker running the container.

`137 = 128 + 9`, so it is a SIGKILL signal, without any more specific reason given. Why would anything sigkill a process in GHA? OOMKill is probably an option. Or maybe GitHub started running ChaosMonkey ;P

https://tldp.org/LDP/abs/html/exitcodes.html

**Comment by jiridanek** [comment]
Notice that container was properly stopped in one of the final cleanup GHA steps...

Also, upload of logs failed with 500 HTTP errors, maybe more things went wrong on GHA side...

I'm thinking two options what to do next

- https://en.wikipedia.org/wiki/Mokusatsu
- add a `sudo dmesg` dump upon failure, assuming we can run that inside container

**Comment by kgiusti** [comment]
ChaosMonkey! Of course! :)

**Comment by jiridanek** [comment]
https://www.githubstatus.com/ says all green. Which maybe means that everything is broken, including monitoring!

**Comment by jiridanek** [comment]
```
[  582.053008] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/actions_job/201eb8b38cc9cafecfbfe1222d53c4f7e32083664a41a206eb4cace034d0fbcf,task=skrouterd,pid=5229,uid=0
[  582.053035] Out of memory: Killed process 5229 (skrouterd) total-vm:[1](https://github.com/skupperproject/skupper-router/actions/runs/3243441690/jobs/5318163122#step:36:1)[33](https://github.com/skupperproject/skupper-router/actions/runs/3243441690/jobs/5318163122#step:36:34)681204712kB, anon-rss:491828kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:[41](https://github.com/skupperproject/skupper-router/actions/runs/3243441690/jobs/5318163122#step:36:42)16kB oom_score_adj:0
```

It's an OOM kill! https://github.com/skupperproject/skupper-router/actions/runs/3243441690/jobs/5318163122#step:33:964

**Comment by jiridanek** [comment]
`anon-rss:383472kB` should be the relevant value for OOM kill. Value of `total-vm` is going to be big anyways, because that always happens with sanitizers, and that should mean nothing. RSS is the actual used memory here.

**Comment by jiridanek** [comment]
/me thinking that tsan is configurable, and there are options that influence how much memory it takes. One of the important ones is the depth of stacktraces to capture, `history_size`, `memory_limit_mb`, and common flag `malloc_context_size`, 

* https://github.com/google/sanitizers/wiki/ThreadSanitizerFlags
* https://github.com/google/sanitizers/wiki/SanitizerCommonFlags

**Comment by jiridanek** [comment]
According to https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

> Hardware specification for Windows and Linux virtual machines:
> 
> 2-core CPU (x86_64)
> 7 GB of RAM
> 14 GB of SSD space

And looking at previous fails, the oom-killed router was occupying something like 481 MB of RSS. Then there is other about 25 routers running at the same time, taking between 248 MB and 34 MB each. See table at https://docs.google.com/spreadsheets/d/1OhB0Kh4sahuMawFRdrJCTlB7yAB1t9dh_PlfgY91OIo/edit the last column.

What test needs 25 routers at the same time? Isn't that a bit extravagant? Can the test maybe detect that tsan is running and be skipped for that? (The disadvantage of messing with the tsan options is that wed get incomplete stacktraces when tsan triggers, because it would not have enough memory to maintain backtraces for each thread and variable access.)

**Comment by ganeshmurthy** [comment]
> According to https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
> 
> > Hardware specification for Windows and Linux virtual machines:
> > 2-core CPU (x86_64)
> > 7 GB of RAM
> > 14 GB of SSD space
> 
> And looking at previous fails, the oom-killed router was occupying something like 481 MB of RSS. Then there is other about 25 routers running at the same time, taking between 248 MB and 34 MB each. See table at https://docs.google.com/spreadsheets/d/1OhB0Kh4sahuMawFRdrJCTlB7yAB1t9dh_PlfgY91OIo/edit the last column.
> 
> What test needs 25 routers at the same time? Isn't that a bit extravagant?

I don't think a single test starts up 25 routers at once. The system_tests_tcp_adaptor.py starts up 9 routers (3 interior and 6 edge routers). Could it be that since we are running tests in parallel, several tests run at the same time and the sum total of all routers started by those tests could be 25 ?

**Comment by jiridanek** [comment]
> I don't think a single test starts up 25 routers at once. The system_tests_tcp_adaptor.py starts up 9 routers (3 interior and 6 edge routers). Could it be that since we are running tests in parallel, several tests run at the same time and the sum total of all routers started by those tests could be 25 ?

🤦🏽 Yes, thats probably it, I should've thought of that. So, the fix should be to change https://github.com/skupperproject/skupper-router/blob/afd6aa191dfb3e9ef47f656f3d75925e25f3485f/.github/workflows/build.yaml#L532 to read what it was some time ago, that is, revert this PR https://github.com/skupperproject/skupper-router/pull/563 here

Maybe there can be 6 tests in parallel, 2 in parallel runs long time...
