### ISSUE TITLE
Throughput improvement possible with TCP buffer changes

### ISSUE THREAD

**Issue by mgoulish** [skupperproject/skupper-router#656]
in tcp_adapter.c, I tripled the TCP_BUFFER_SIZE, and also tripled WRITE_BUFFERS.

In my loopback throughput testing this resulted in a 22% throughput increase -- from 15.5 to 18.9 Gbits/sec (in a test with 4 router threads and 4 Iperf threads).

Latency was unchanged across the spectrum ( < 1 microsecond difference ) up to the 99.999% point, at which the changed code was slight faster than the unchanged code (6  microseconds).

I experimented by changing or not changing all combinations of
  TCP_BUFFER_SIZE
  TCP_MAX_CAPACITY, and
  WRITE_BUFFERS.

Changing TCP_MAX_CAPACITY had no effect that I could measure.

Because the router had 4 worker threads, I gave it 7 threads total and locked them all in place on odd-numbered cores using 'numactl'.

**Comment by ganeshmurthy** [comment]
How does tripling the TCP_BUFFER_SIZE and WRITE_BUFFERS affect the memory on the router when there are hundreds of connections all pumping the maximum data into the router ?

**Comment by grs** [comment]
On Thu, Aug 4, 2022 at 7:42 PM Michael Goulish ***@***.***>
wrote:

> in tcp_adapter.c, I tripled the TCP_BUFFER_SIZE, and also tripled
> WRITE_BUFFERS.
>

What do you see just tripling WRITE_BUFFERS? Would also be good to test on
something other than loopback, where there may be underlying limits in how
much can be written at a time anyway.

**Comment by mgoulish** [comment]
Ganesh -- I think it would add about 3.5 MB per connection.

**Comment by mgoulish** [comment]
GRS -- 

no change: 15.5 Gbits/sec
only WRITE_BUFFERS tripled :  16.0 Gbits/sec
only TCP_BUFFER_SIZE tripled:  18.4 Gbits/sec
WRITE_BUFFERS and TCP_BUFFER_SIZE both tripled : 18.9 Gbits/sec

Hmm.
Now that you mention it ... I got most of the mileage by only tripling the buffer size...

**Comment by ganeshmurthy** [comment]
Was just curious how increasing the size of the amqp buffers help ? Currently the amqp buffer size is set to 512 bytes here - https://github.com/skupperproject/skupper-router/blob/main/include/qpid/dispatch/buffer.h#L36

**Comment by ganeshmurthy** [comment]
We are moving to the process of moving to the tcp lite adaptor, not making any more updates to the existing tcp adaptor
