### ISSUE TITLE
system_tests_edge_router.StreamingMessageTest failure Process 3947 (name=clogger) error: expected -15 but actual returncode is 1

### ISSUE THREAD

**Issue by kgiusti** [skupperproject/skupper-router#667]
https://github.com/skupperproject/skupper-router/runs/7679402985?check_suite_focus=true#step:29:2825

self = <tests.system_tests_edge_router.StreamingMessageTest testMethod=test_11_streaming_closest_parallel>

    def teardown(self):
        """Clean up (tear-down, stop or close) objects recorded via cleanup()"""
        self.cleanup_list.reverse()
        errors = []
        for obj in self.cleanup_list:
            try:
                for method in ["teardown", "tearDown", "stop", "close"]:
                    cleanup = getattr(obj, method, None)
                    if cleanup:
                        cleanup()
                        break
            except Exception as exc:
                errors.append(exc)
        if errors:
>           raise RuntimeError("Errors during teardown: \n\n%s" % "\n\n".join([str(e) for e in errors]))
E           RuntimeError: Errors during teardown: 
E           
E           Process 3947 (name=clogger) error: expected -15 but actual returncode is 1
E           clogger -a amqp://0.0.0.0:26389 -c 1 -t closest/test-address -s 4294967295 -D -P 100

**Comment by jiridanek** [comment]
This is very probably related to

* https://github.com/skupperproject/skupper-router/issues/244

**Comment by kgiusti** [comment]
Oh most definitely the same - the test client doesn't handle delivery abort properly!  Good catch - I need to search open issues before piling more on.
