### ISSUE TITLE
[coverity] double_free: Calling `qd_free_http_adaptor_config` frees pointer `config` which has already been freed

### ISSUE THREAD

**Issue by jiridanek** [skupperproject/skupper-router#677]
![image](https://user-images.githubusercontent.com/442720/183633993-689eef4a-e988-42d2-9824-7ed5638e6269.png)

![image](https://user-images.githubusercontent.com/442720/183634473-d88d8b04-4037-400b-9fb0-a49cc02f5ac4.png)

The first report is correct, the second is just Coverity being dumb and unable to figure out that when `config` is freed, the function always returns early and the access it complains about does not happen. The fix for the first reported issue should cause the second false-positive go away.

**Comment by kgiusti** [comment]
Oh my.

If the idea is to transfer ownership of the *config memory it would probably be a lot more foolproof to make qd_load_http_adaptor_config() a constructor that returns the *config on success.
