### ISSUE TITLE
[coverity] missing_argument: No argument for format specifier `%s`

### ISSUE THREAD

**Issue by jiridanek** [skupperproject/skupper-router#682]
![image](https://user-images.githubusercontent.com/442720/183639040-c17c111f-1d8c-49eb-a983-634bcc96ba0a.png)

**Comment by ganeshmurthy** [comment]
I have fixed this in https://github.com/skupperproject/skupper-router/pull/664

**Comment by ganeshmurthy** [comment]
Fixed by https://github.com/skupperproject/skupper-router/commit/a4ecedae4bdbfa68357b5ab30be013feadd90480
