### ISSUE TITLE
clang-format attempts to reformat skrouterd.json - non-C files should not be reformatted

### ISSUE THREAD

**Issue by kgiusti** [skupperproject/skupper-router#725]

**Comment by kgiusti** [comment]
workaround: remove the pre-commit hook from your local repo if you've installed it:

$ pre-commit uninstall

Run 'git clang-format' by hand and 'git restore [path]/skrouterd.json' prior to committing the change.

**Comment by ganeshmurthy** [comment]
> workaround: remove the pre-commit hook from your local repo if you've installed it:
> 
> $ pre-commit uninstall
> 
> Run 'git clang-format' by hand and 'git restore [path]/skrouterd.json' prior to committing the change.

The above instructions worked for me. Thanks.

**Comment by jiridanek** [comment]
> workaround: remove the pre-commit hook from your local repo if you've installed it:

why remove the hook? simply commit with `git commit --no-verify` which skips running the hook for that commit.

The rest (`git restore`) is IMO good advice, that can be used together with --no-verify
