### ISSUE TITLE
Test enhancement: Integrate nginx into CI for HTTP/x testing

### ISSUE THREAD

**Issue by kgiusti** [skupperproject/skupper-router#857]
Most of the HTTP/1 tests use the HTTPServer and BaseHTTPRequestHandler from the python library as the test server. This should be replaced with nginx wherever possible:

1. nginx is a very popular http server that is production grade and would make a better verification tool than the python server. In fact the python docs for the server do NOT recommend using the python server in production!
2. currently the python server requires a boatload of python hacking to work around its deficiencies and makes me a Sad Panda because it seems that every time I need to update/fix a test involving that python http server I invite it to vomit up a swirling torrent of pain points that are apparently designed to make my life as miserable as possible [end of rant :P ].

Exactly how nginx can be integrated into CI (and run in GHA) is TBD: containers? Non-root user? etc?

**Comment by jiridanek** [comment]
Possibly either https://github.com/testcontainers/testcontainers-python or the old-style way: require server binary on PATH and run on nonprivileged ports in subprocess (skip test if server binary is not present).

nginx can be installed from npm, https://www.npmjs.com/package/nginx-binaries but apparently nobody uploaded it to pypi yet
