### ISSUE TITLE
Compile warnings from cproton_ffi.c

### ISSUE THREAD

**Issue by jiridanek** [skupperproject/skupper-router#931]
https://github.com/skupperproject/skupper-router/actions/runs/4056555498/jobs/6981190135#step:17:331

```
cproton_ffi.c: In function ‘pn_event_class_name_py’:
cproton_ffi.c:643:25: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  643 |     pn_class_t *class = pn_event_class(event);
      |                         ^~~~~~~~~~~~~~
cproton_ffi.c:644:41: warning: pointer type mismatch in conditional expression
  644 |     return class ? pn_class_name(class) : class;
      |                                         ^
```

I'm not creating Proton issue because here it feels much lower profile in case the warnings are harmless (and known).

**Comment by jiridanek** [comment]
@astitcher We've gotten desensitised to Proton build warnings in the swig era. So, now might be time to look at the warnings again.

**Comment by astitcher** [comment]
Indeed, this one might just be a stupid mistake on my part actually. - I'll take a look.

**Comment by astitcher** [comment]
Yep, sloppy programming on my part.

**Comment by astitcher** [comment]
Fixed
