### ISSUE TITLE
CMake is failing to build Proton due to filesystem operations copying C sources around

### ISSUE THREAD

**Issue by jiridanek** [skupperproject/skupper-router#936]
```
Error copying directory from "/home/runner/work/skupper-router/skupper-router/qpid-proton/c/include" to "include".
```

https://github.com/skupperproject/skupper-router/actions/runs/4075507316/jobs/7021992696#step:17:129

Parallel build is likely to blame, https://issues.apache.org/jira/browse/PROTON-2679

**Comment by jiridanek** [comment]
There was commit that was supposed to fix something similar, https://github.com/apache/qpid-proton/commit/833bf2ffa8796a313e5c43c4276229eddeb0affd. Either it did not work, or this is in different place.

**Comment by astitcher** [comment]
Is this a Proton build issue? If so shouldn't this be in the Proton jira or github?

**Comment by astitcher** [comment]
I've never seen an issue like this when building Proton itself.
Another thing - typically I recommend using ninja as the buildsystem a rather than gmake as I find that it's faster and more reliable.

**Comment by jiridanek** [comment]
Thanks, I'll use this issue to switch CI to ninja; I'll also switch the container image, hopefully @ajssmith / @mcressman (whoever now does the builds) will also approve.

**Comment by jiridanek** [comment]
> Thanks, I'll use this issue to switch CI to ninja; I'll also switch the container image, hopefully @ajssmith / @mcressman (whoever now does the builds) will also approve.

Actually, this is not so simple. `ninja-build` is not part of ubi8, so it is necessary to either pick it from CentOS, or subscribe the RHEL image and enable CodeReady Builder channel. Neither of which looks particularly palletable to me. In addition, ninja rpm depends on Python 3.6, so now there is multiple versions of Python in the build image, opening opportunities for confusion in the future.

Example of going the CentOS route is https://serverfault.com/a/1121861/116739 and this is what the Containerfile used to do before all necessary deps were added to ubi8. We could try requesting ninja-build in ubi8, as it was done with the other packages, see bugzillas linked in comments on https://issues.redhat.com/browse/SKUPPER-6.

**Comment by astitcher** [comment]
> I've never seen an issue like this when building Proton itself.
I'm not saying that this isn't the same underlying issue I fixed in PROTON-2679 - it certainly looks like it just that ninja is more featureful and hence a bit more reliable when expressing dependencies for CMake. We should make the build work for all buildsystems ideally, but it seems that CMake is pretty finicky when expressing dependencies between custom_targets and everything else.

**Comment by astitcher** [comment]
Actually when I made the change for PROTON-2679 I wasn't sure it would fix the issue - looks like it didn't completely - I hate the unintuitive (to me at least) way that dependencies work with custom targets and custom commands

**Comment by astitcher** [comment]
I found another issue with the python build dependencies and fixed it - hopefully this should make this problem go away.
