### ISSUE TITLE
system_tests_grpc test failures: Waiting for thread pool to idle before forking

### ISSUE THREAD

**Issue by kgiusti** [skupperproject/skupper-router#950]
In the logs:

E0206 19:19:43.124373069    3049 thread_pool.cc:254]                   Waiting for thread pool to idle before forking

**Comment by kgiusti** [comment]
Seems to be a grpc bug:

https://github.com/grpc/grpc/issues/31885

**Comment by gnossen** [comment]
Please note that `grpcio==1.52.0` has been yanked so this should not affect new installs unless you have explicitly pinned to `grpcio==1.52.0`.

**Comment by ganeshmurthy** [comment]
Thanks @gnossen 

We do not pin the version of grpcio as seen here - https://github.com/skupperproject/skupper-router/blob/main/requirements-dev.txt#L35 , so we should fall back to the latest released version of grpcio which I am guessing is 1.51.1 since 1.53.0 is still being worked on and 1.52.0 has been yanked.

**Comment by jiridanek** [comment]
@ganeshmurthy no need to guess 😜 

```
Collecting grpcio
  Downloading grpcio-1.51.1-cp[39](https://github.com/skupperproject/skupper-router/actions/runs/4118151345/jobs/7110376300#step:8:40)-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 133.5 MB/s eta 0:00:00
```

https://github.com/skupperproject/skupper-router/actions/runs/4118151345/jobs/7110376300#step:8:39

@gnossen The https://github.com/grpc/grpc/issues/31885 is reported against grpc 1.51.1 (from the first comment), so I don't understand what the relevance of 1.52.0 being pulled is.

We generate code from our .proto file in an offline step and commit the result to the repository, so our generated code was created quite long time ago, looks like 8 months ago, judging from https://github.com/skupperproject/skupper-router/pull/525.

**Comment by kgiusti** [comment]
@jiridanek 
Sorry: I should've included a reference to the actual test failure:

https://github.com/skupperproject/skupper-router/actions/runs/4107104544/jobs/7086169621#step:30:1487

In that particular run it appears to be installing grpcio grpcio-1.52.0:

https://github.com/skupperproject/skupper-router/actions/runs/4107104544/jobs/7086169621#step:27:50

@gnossen Thanks!

**Comment by jiridanek** [comment]
That build I just linked did not fail with the "Waiting for thread pool" message, it also timeouted, but (probably) for different reason. The CI job with that message was using 1.52.0, because then it was not yet yanked, probably,

```
Collecting grpcio
  Downloading grpcio-1.52.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.9 MB)
25l     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/4.9 MB ? eta -:--:--
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 245.4 MB/s eta 0:00:00
```

https://github.com/skupperproject/skupper-router/actions/runs/4107104544/jobs/7086169621#step:27:49

**Comment by ganeshmurthy** [comment]
> @ganeshmurthy no need to guess stuck_out_tongue_winking_eye
> 
> ```
> Collecting grpcio
>   Downloading grpcio-1.51.1-cp[39](https://github.com/skupperproject/skupper-router/actions/runs/4118151345/jobs/7110376300#step:8:40)-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.8 MB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 133.5 MB/s eta 0:00:00
> ```
> 
> https://github.com/skupperproject/skupper-router/actions/runs/4118151345/jobs/7110376300#step:8:39
> 
> @gnossen The [grpc/grpc#31885](https://github.com/grpc/grpc/issues/31885) is reported against grpc 1.51.1 (from the first comment), so I don't understand what the relevance of 1.52.0 being pulled is.

https://github.com/grpc/grpc/issues/31885#issuecomment-1419863899
(for some people (including us) the issue seems to be reproduced only with version 1.52.0)

**Comment by kgiusti** [comment]
> That build I just linked did not fail with the "Waiting for thread pool" message, it also timeouted during grpc test, but (probably) for different reason. The CI job with that message was using 1.52.0, because then it was not yet yanked, probably,
> 
> ```
> Collecting grpcio
>   Downloading grpcio-1.52.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.9 MB)
> 25l     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/4.9 MB ? eta -:--:--
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 245.4 MB/s eta 0:00:00
> ```
> 
> https://github.com/skupperproject/skupper-router/actions/runs/4107104544/jobs/7086169621#step:27:49

Agreed - just bad timing I suppose.

I'm closing this as Not A Bug.
