### ISSUE TITLE
AssertionError: b'abcd' != b'' : ncat command returned invalid data, expected b'abcd' but got b''

### ISSUE THREAD

**Issue by jiridanek** [skupperproject/skupper-router#957]
About CI, I'm seeing there https://github.com/skupperproject/skupper-router/actions/runs/4167633719/jobs/7213457157#step:30:8856
> 
> ```
> E       AssertionError: b'abcd' != b'' : ncat command returned invalid data, expected b'abcd' but got b''
> ```
> 
> is this something that recently appeared again? I remember something like this was already fixed in #391

It does indeed look the same. Please create a github issue and I will take a look. Thanks.

_Originally posted by @ganeshmurthy in https://github.com/skupperproject/skupper-router/issues/956#issuecomment-1430218199_

**Comment by ganeshmurthy** [comment]
We are now moving to the new TCP Lite adaptor. Closing this issue
