### ISSUE TITLE
InvalidVersion error thrown during Python package  build: version number is not PEP-440 compliant

### ISSUE THREAD

**Issue by kgiusti** [skupperproject/skupper-router#973]
Router build issues the following very scary message:

/home/kgiusti/.local/lib/python3.11/site-packages/setuptools/_normalization.py:93: SetuptoolsDeprecationWarning: Invalid version: '2.1.0-149-g45d75bbf'.
        !!
        ###################
        # Invalid version #
        ###################
        '2.1.0-149-g45d75bbf' is not valid according to PEP 440.
 
        Please make sure specify a valid version for your package.
        Also note that future releases of setuptools may halt the build process
        if an invalid version is given.
        
 
!!
  warnings.warn(cleandoc(msg), SetuptoolsDeprecationWarning)

See https://peps.python.org/pep-0440/#version-scheme

Need to reformat the version to something compliant: maybe 2.1.0.dev149+g45d75bbf ??

**Comment by jiridanek** [comment]
also, https://github.com/jiridanek/skupper-router/actions/runs/4514232572/jobs/7950069120#step:25:661

```
/usr/lib/python3.11/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: UNKNOWN is an invalid version and will not be supported in a future release
```

**Comment by jiridanek** [comment]
and, in copr rpm builds on fedora 38 and rawhide (but not on fedora 37)

```
Processing files: skupper-router-0.0.git.3973.71ba5332-2.20230328192824435834.pr1014.172.g71ba5332.fc38.s390x
Traceback (most recent call last):
  File "/usr/lib/rpm/pythondistdeps.py", line 622, in <module>
    main()
  File "/usr/lib/rpm/pythondistdeps.py", line 481, in main
    if RpmVersion(version).is_zero():
       ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/rpm/pythondistdeps.py", line 135, in __init__
    version = parse(version_id)
              ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/packaging/version.py", line 52, in parse
    return Version(version)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '0.0.git.3973.71ba5332'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/rpm/pythondistdeps.py", line 625, in <module>
    raise RuntimeError("Error: pythondistdeps.py generator encountered an unhandled exception and was terminated.") from exc
RuntimeError: Error: pythondistdeps.py generator encountered an unhandled exception and was terminated.
```
https://copr.fedorainfracloud.org/coprs/packit/skupperproject-skupper-router-1014/build/5718920/

**Comment by ganeshmurthy** [comment]
Closing this in favor of https://github.com/skupperproject/skupper-router/issues/1251 which has a more recent version number
